### ISSUE TITLE
Allow this script to take leap-years into account.

### ISSUE THREAD

**Issue by sklusz** [tklusz/Simple-Daily-Wallpaper#1]
Currently, this script doesn't take leap-years into account for the day calculation. This should be able to easily be fixed with a single function. Leaving this open for new users or if you want to contribute for Hacktoberfest.

**Comment by angelbarrera92** [comment]
Can i take It?

**Comment by sklusz** [comment]
@angelbarrera92 go ahead!

**Comment by sklusz** [comment]
Copying this from another comment:

When there's a leap year, there is a 29th day of February. Normally March 1st is the 60th day of the year, but on leap years March 1st is the 61st day of the year.

There should be some way to have March 1st still be Wallpaper number 60, instead of Wallpaper number 61 on a leap year. It's not necessary to allow a user to set a unique wallpaper for February 29th (so it's only shown on leap years) but if you would like to do that somehow, go ahead.
